// styles/gm.js
// Stili "Velluto teatrale" per le schermate GM:
// RoomList, CreateRoom, Dashboard, PlayerDetail.

import { StyleSheet, Platform } from 'react-native';
import { colors, spacing, radius, fontSize, shadows, fontFamilies } from './theme';

const v = colors.velvet;

const brassShadow = Platform.select({
  web: {
    shadowColor: v.gold,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 18,
  },
  default: {
    shadowColor: v.gold,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
});

const cardShadow = Platform.select({
  web: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.45,
    shadowRadius: 18,
  },
  default: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
});

// ---------------------------------------------------------------------------
// CreateRoomScreen
// ---------------------------------------------------------------------------
export const createRoomStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: v.bgDeep },
  container: {
    flexGrow: 1,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.huge,
  },
  stage: {
    flex: 1,
    minHeight: 700,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
    zIndex: 1,
  },
  ornamentTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginBottom: spacing.md,
    opacity: 0.85,
  },
  ornamentLine: { width: 64, height: 1, backgroundColor: v.goldFaintStrong },
  ornamentDot: {
    width: 6, height: 6, borderRadius: 3,
    backgroundColor: v.gold,
    transform: [{ rotate: '45deg' }],
  },
  eyebrow: {
    color: v.gold,
    fontSize: fontSize.xs,
    letterSpacing: 4,
    textTransform: 'uppercase',
    textAlign: 'center',
    marginBottom: spacing.md,
    fontFamily: fontFamilies.body,
  },
  card: {
    width: '100%',
    maxWidth: 540,
    backgroundColor: 'rgba(61,30,37,0.92)',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: v.goldFaint,
    paddingHorizontal: 28,
    paddingTop: 32,
    paddingBottom: 28,
    ...cardShadow,
  },
  title: {
    fontFamily: fontFamilies.serif,
    fontSize: 30,
    fontWeight: '700',
    color: v.champagne,
    textAlign: 'center',
    letterSpacing: 1.5,
    marginBottom: spacing.sm,
  },
  subtitle: {
    fontFamily: fontFamilies.serif,
    fontStyle: 'italic',
    color: v.champagneMuted,
    fontSize: fontSize.md,
    textAlign: 'center',
    marginBottom: spacing.xxl,
  },
  label: {
    color: v.champagneMuted,
    fontSize: fontSize.xs,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: spacing.md,
    fontFamily: fontFamilies.body,
  },
  input: {
    backgroundColor: v.bgRaised,
    borderWidth: 0,
    borderBottomWidth: 1.5,
    borderBottomColor: v.goldFaint,
    borderTopLeftRadius: radius.sm,
    borderTopRightRadius: radius.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    fontSize: fontSize.lg,
    color: v.champagne,
    fontFamily: fontFamilies.body,
  },
  pickerWrapper: {
    backgroundColor: v.bgRaised,
    borderWidth: 0,
    borderBottomWidth: 1.5,
    borderBottomColor: v.goldFaint,
    borderTopLeftRadius: radius.sm,
    borderTopRightRadius: radius.sm,
    overflow: 'hidden',
  },
  picker: {
    color: v.champagne,
    backgroundColor: 'transparent',
    fontFamily: fontFamilies.body,
  },
  // Segmented control timer
  segmentRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  segment: {
    paddingHorizontal: spacing.md + 2,
    paddingVertical: 10,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: v.goldFaintStrong,
    backgroundColor: 'rgba(74,37,48,0.6)',
  },
  segmentActive: {
    backgroundColor: v.gold,
    borderColor: v.goldSoft,
    ...brassShadow,
  },
  segmentText: {
    color: v.goldSoft,
    fontSize: fontSize.md,
    fontFamily: fontFamilies.body,
    letterSpacing: 1,
  },
  segmentTextActive: {
    color: v.ink,
    fontWeight: '700',
  },
  ctaWrapper: {
    width: '100%',
    marginTop: spacing.xxl,
  },
  ctaGlow: {
    position: 'absolute',
    top: -3, left: -3, right: -3, bottom: -3,
    borderRadius: radius.md + 3,
    borderWidth: 1,
    borderColor: v.gold,
    ...brassShadow,
  },
  button: {
    width: '100%',
    backgroundColor: v.gold,
    paddingVertical: 16,
    borderRadius: radius.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: v.goldSoft,
  },
  buttonDisabled: { backgroundColor: v.taupe, borderColor: v.taupe },
  buttonText: {
    color: v.ink,
    fontSize: fontSize.lg,
    fontFamily: fontFamilies.serif,
    fontWeight: '700',
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  errorBanner: {
    backgroundColor: 'rgba(168,89,89,0.18)',
    borderLeftWidth: 3,
    borderLeftColor: v.gold,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: radius.sm,
    marginTop: spacing.lg,
  },
  errorBannerText: {
    color: '#f1c8c8',
    fontSize: fontSize.sm,
    fontFamily: fontFamilies.body,
  },
});

// ---------------------------------------------------------------------------
// RoomListScreen
// ---------------------------------------------------------------------------
export const roomListStyles = StyleSheet.create({
  listFrame: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  list: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: 120,
    maxWidth: 920,
    width: '100%',
    alignSelf: 'center',
  },
  centered: {
    flex: 1,
    backgroundColor: v.bgDeep,
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.md,
  },
  loadingText: { color: v.champagneMuted, fontSize: fontSize.base, fontFamily: fontFamilies.body },
  // Header sezione
  headerBlock: {
    marginBottom: spacing.xl,
    paddingHorizontal: spacing.xs,
  },
  eyebrow: {
    color: v.gold,
    fontSize: fontSize.xs,
    letterSpacing: 4,
    textTransform: 'uppercase',
    marginBottom: 6,
    fontFamily: fontFamilies.body,
  },
  title: {
    fontFamily: fontFamilies.serif,
    fontSize: 34,
    fontWeight: '700',
    color: v.champagne,
    letterSpacing: 1.5,
  },
  titleRule: {
    height: 1,
    backgroundColor: v.goldFaint,
    marginTop: spacing.md,
  },
  // Card
  card: {
    backgroundColor: 'rgba(61,30,37,0.92)',
    borderRadius: radius.lg,
    paddingVertical: 18,
    paddingHorizontal: 20,
    marginBottom: spacing.md + 2,
    borderWidth: 1,
    borderColor: v.goldFaint,
    ...cardShadow,
  },
  cardOpen: {
    borderColor: 'rgba(122,163,122,0.6)',
  },
  cardClosed: {
    borderColor: 'rgba(168,89,89,0.4)',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.md,
    gap: spacing.md,
  },
  cardName: {
    fontFamily: fontFamilies.serif,
    fontSize: fontSize.xxl,
    fontWeight: '700',
    color: v.champagne,
    flex: 1,
    letterSpacing: 0.8,
  },
  // Brass plate per il codice stanza
  brassPlate: {
    backgroundColor: v.gold,
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: v.goldSoft,
  },
  brassPlateText: {
    color: v.ink,
    fontFamily: fontFamilies.serif,
    fontSize: fontSize.md,
    fontWeight: '700',
    letterSpacing: 4,
  },
  // Stato
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  statusDot: {
    width: 8, height: 8, borderRadius: 4,
  },
  statusDotOpen: { backgroundColor: v.success, shadowColor: v.success, shadowOpacity: 0.8, shadowRadius: 6 },
  statusDotClosed: { backgroundColor: v.taupe },
  statusText: {
    color: v.champagneMuted,
    fontSize: fontSize.xs,
    letterSpacing: 2,
    textTransform: 'uppercase',
    fontFamily: fontFamilies.body,
  },
  // Info dettagli
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  infoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs + 2,
  },
  infoIcon: {
    color: v.gold,
    fontSize: fontSize.sm,
  },
  infoText: {
    color: v.champagneMuted,
    fontSize: fontSize.sm,
    fontFamily: fontFamilies.body,
  },
  // Azioni
  actionsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: v.goldFaint,
  },
  actionButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: radius.sm,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    borderWidth: 1,
  },
  enterButton: {
    backgroundColor: v.gold,
    borderColor: v.goldSoft,
  },
  enterButtonText: {
    color: v.ink,
    fontSize: fontSize.sm,
    fontFamily: fontFamilies.body,
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  ghostButton: {
    backgroundColor: 'transparent',
    borderColor: v.goldFaintStrong,
  },
  ghostButtonText: {
    color: v.goldSoft,
    fontSize: fontSize.sm,
    fontFamily: fontFamilies.body,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  dangerGhost: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(168,89,89,0.5)',
  },
  dangerGhostText: {
    color: '#d49191',
    fontSize: fontSize.sm,
    fontFamily: fontFamilies.body,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  buttonDisabled: { opacity: 0.4 },
  // Stato vuoto
  emptyContainer: {
    alignItems: 'center',
    marginTop: 80,
    gap: spacing.sm,
    paddingHorizontal: spacing.xl,
  },
  emptyOrnament: {
    fontSize: 40,
    color: v.goldFaintStrong,
    marginBottom: spacing.md,
  },
  emptyText: {
    fontSize: fontSize.xl,
    color: v.champagne,
    fontFamily: fontFamilies.serif,
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  emptySubtext: {
    fontSize: fontSize.md,
    color: v.champagneMuted,
    fontFamily: fontFamilies.serif,
    fontStyle: 'italic',
    textAlign: 'center',
  },
  // FAB Crea nuova stanza
  fabContainer: {
    position: 'absolute',
    right: spacing.xl,
    bottom: spacing.xl,
    zIndex: 50,
  },
  fabGlow: {
    position: 'absolute',
    top: -4, left: -4, right: -4, bottom: -4,
    borderRadius: radius.md + 4,
    borderWidth: 1,
    borderColor: v.gold,
    ...brassShadow,
  },
  fab: {
    backgroundColor: v.gold,
    paddingVertical: 14,
    paddingHorizontal: spacing.xl,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: v.goldSoft,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  fabText: {
    color: v.ink,
    fontSize: fontSize.md,
    fontFamily: fontFamilies.serif,
    fontWeight: '700',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  // Header
  headerButton: {
    paddingHorizontal: spacing.md + 2,
    paddingVertical: 6,
  },
  headerButtonText: {
    color: v.goldSoft,
    fontSize: fontSize.base,
    fontFamily: fontFamilies.body,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
});

// ---------------------------------------------------------------------------
// DashboardScreen
// ---------------------------------------------------------------------------
export const dashboardStyles = StyleSheet.create({
  list: { flex: 1, backgroundColor: v.bgDeep },
  listContent: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.huge,
    maxWidth: 920,
    width: '100%',
    alignSelf: 'center',
  },
  // Hero strip con brass plate centrale
  hero: {
    alignItems: 'center',
    marginBottom: spacing.xxl,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
    backgroundColor: 'rgba(61,30,37,0.6)',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: v.goldFaint,
    ...cardShadow,
  },
  heroEyebrow: {
    color: v.gold,
    fontSize: fontSize.xs,
    letterSpacing: 4,
    textTransform: 'uppercase',
    marginBottom: spacing.sm,
    fontFamily: fontFamilies.body,
  },
  brassPlateBig: {
    backgroundColor: v.gold,
    paddingHorizontal: spacing.xxl,
    paddingVertical: 14,
    borderRadius: radius.sm,
    borderWidth: 1.5,
    borderColor: v.goldSoft,
    marginBottom: spacing.md,
    ...brassShadow,
  },
  brassPlateBigText: {
    color: v.ink,
    fontFamily: fontFamilies.serif,
    fontSize: 40,
    fontWeight: '700',
    letterSpacing: 10,
  },
  heroStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  heroStatusDot: {
    width: 8, height: 8, borderRadius: 4,
  },
  heroStatusDotOpen: { backgroundColor: v.success },
  heroStatusDotClosed: { backgroundColor: v.danger },
  heroStatusText: {
    color: v.champagneMuted,
    fontSize: fontSize.xs,
    letterSpacing: 3,
    textTransform: 'uppercase',
    fontFamily: fontFamilies.body,
  },
  // Section title
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontFamily: fontFamilies.serif,
    fontSize: fontSize.xxl,
    fontWeight: '700',
    color: v.champagne,
    letterSpacing: 0.8,
  },
  sectionCount: {
    color: v.gold,
    fontSize: fontSize.md,
    fontFamily: fontFamilies.body,
    letterSpacing: 2,
  },
  // Player card
  playerCard: {
    backgroundColor: 'rgba(61,30,37,0.92)',
    borderRadius: radius.lg,
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginBottom: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: v.goldFaint,
    gap: spacing.md,
    ...cardShadow,
  },
  playerCardInfo: { flex: 1, gap: 6 },
  playerName: {
    color: v.champagne,
    fontFamily: fontFamilies.serif,
    fontSize: fontSize.lg,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  playerSceneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  scenePill: {
    backgroundColor: 'rgba(200,164,90,0.15)',
    borderWidth: 1,
    borderColor: v.goldFaintStrong,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: radius.pill,
  },
  scenePillText: {
    color: v.goldSoft,
    fontSize: fontSize.xs,
    fontFamily: fontFamilies.body,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  removeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(168,89,89,0.5)',
    backgroundColor: 'rgba(168,89,89,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeButtonText: {
    color: '#d49191',
    fontSize: fontSize.lg,
    fontWeight: 'bold',
  },
  // Empty
  emptyContainer: {
    alignItems: 'center',
    paddingVertical: 60,
    gap: spacing.md,
  },
  emptyDot: {
    width: 10, height: 10, borderRadius: 5,
    backgroundColor: v.gold,
  },
  emptyText: {
    color: v.champagneMuted,
    fontFamily: fontFamilies.serif,
    fontStyle: 'italic',
    fontSize: fontSize.md,
    textAlign: 'center',
  },
  // Footer close button
  closeButtonWrapper: {
    marginTop: spacing.xl,
    alignItems: 'center',
  },
  closeButton: {
    paddingVertical: 14,
    paddingHorizontal: spacing.xxl,
    borderRadius: radius.md,
    alignItems: 'center',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(168,89,89,0.55)',
  },
  closeButtonDisabled: {
    borderColor: v.taupe,
    opacity: 0.5,
  },
  closeButtonText: {
    color: '#d49191',
    fontSize: fontSize.md,
    fontFamily: fontFamilies.body,
    fontWeight: '600',
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  // Header
  headerButton: {
    paddingHorizontal: spacing.md + 2,
    paddingVertical: 6,
  },
  headerButtonText: {
    color: v.goldSoft,
    fontSize: fontSize.base,
    fontFamily: fontFamilies.body,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
});

// ---------------------------------------------------------------------------
// PlayerDetailScreen
// ---------------------------------------------------------------------------
export const playerDetailStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: v.bgDeep },
  list: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  listContent: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xl,
    paddingBottom: spacing.huge,
    maxWidth: 820,
    width: '100%',
    alignSelf: 'center',
  },
  // Header
  header: {
    backgroundColor: 'rgba(61,30,37,0.92)',
    borderRadius: radius.lg,
    paddingHorizontal: 22,
    paddingVertical: 20,
    marginBottom: spacing.xl,
    borderWidth: 1,
    borderColor: v.goldFaint,
    ...cardShadow,
  },
  headerEyebrow: {
    color: v.gold,
    fontSize: fontSize.xs,
    letterSpacing: 4,
    textTransform: 'uppercase',
    marginBottom: 6,
    fontFamily: fontFamilies.body,
  },
  playerName: {
    fontFamily: fontFamilies.serif,
    fontSize: 28,
    fontWeight: '700',
    color: v.champagne,
    letterSpacing: 1,
    marginBottom: spacing.sm,
  },
  playerSceneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  sceneBadge: {
    backgroundColor: 'rgba(200,164,90,0.15)',
    borderWidth: 1,
    borderColor: v.goldFaintStrong,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.pill,
  },
  sceneBadgeText: {
    color: v.goldSoft,
    fontSize: fontSize.xs,
    fontFamily: fontFamilies.body,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  playerScene: {
    color: v.champagneMuted,
    fontSize: fontSize.sm,
    fontFamily: fontFamilies.body,
  },
  // Section title
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  sectionTitle: {
    fontFamily: fontFamilies.serif,
    fontSize: fontSize.xxl,
    fontWeight: '700',
    color: v.champagne,
    letterSpacing: 0.8,
  },
  sectionCount: {
    color: v.gold,
    fontSize: fontSize.md,
    fontFamily: fontFamilies.body,
    letterSpacing: 2,
  },
  // Timeline
  progressItem: {
    flexDirection: 'row',
    marginBottom: 0,
  },
  timelineColumn: {
    width: 36,
    alignItems: 'center',
  },
  timelineDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    marginTop: spacing.xs + 2,
    borderWidth: 2,
    borderColor: v.gold,
    backgroundColor: 'transparent',
  },
  dotSolved: {
    backgroundColor: v.gold,
    shadowColor: v.gold,
    shadowOpacity: 0.6,
    shadowRadius: 6,
  },
  dotPending: {
    backgroundColor: 'transparent',
    borderColor: v.goldFaintStrong,
  },
  timelineLine: {
    width: 1,
    flex: 1,
    backgroundColor: v.goldFaint,
    minHeight: 40,
    marginTop: 2,
  },
  progressContent: {
    flex: 1,
    backgroundColor: 'rgba(61,30,37,0.85)',
    borderRadius: radius.md,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginLeft: spacing.sm,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: v.goldFaint,
  },
  progressScene: {
    fontFamily: fontFamilies.serif,
    fontSize: fontSize.lg,
    fontWeight: '600',
    color: v.champagne,
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  progressTime: {
    fontSize: fontSize.xs,
    color: v.champagneMuted,
    marginBottom: 4,
    fontFamily: fontFamilies.body,
    letterSpacing: 1,
  },
  progressStatus: {
    fontSize: fontSize.xs,
    fontFamily: fontFamilies.body,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  statusSolved: { color: v.success },
  statusPending: { color: v.gold },
  emptyText: {
    textAlign: 'center',
    color: v.champagneMuted,
    fontFamily: fontFamilies.serif,
    fontStyle: 'italic',
    marginVertical: spacing.xl,
    fontSize: fontSize.md,
  },
  // Sent hints
  sentHintsContainer: {
    backgroundColor: 'rgba(74,37,48,0.7)',
    borderRadius: radius.md,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginTop: spacing.lg,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: v.goldFaint,
  },
  sentHintsTitle: {
    fontSize: fontSize.xs,
    color: v.gold,
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 8,
    fontFamily: fontFamilies.body,
  },
  sentHintText: {
    fontSize: fontSize.sm,
    color: v.champagneMuted,
    lineHeight: 20,
    fontFamily: fontFamilies.body,
    marginBottom: 2,
  },
  // Hint composer
  hintSection: {
    backgroundColor: 'rgba(61,30,37,0.92)',
    borderRadius: radius.lg,
    paddingHorizontal: 20,
    paddingVertical: 18,
    marginTop: spacing.lg,
    borderWidth: 1,
    borderColor: v.goldFaint,
    ...cardShadow,
  },
  hintLabel: {
    fontSize: fontSize.xs,
    color: v.gold,
    letterSpacing: 3,
    textTransform: 'uppercase',
    marginBottom: spacing.sm + 2,
    fontFamily: fontFamilies.body,
  },
  hintInput: {
    backgroundColor: v.bgRaised,
    borderWidth: 1,
    borderColor: v.goldFaint,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    fontSize: fontSize.md,
    minHeight: 70,
    textAlignVertical: 'top',
    color: v.champagne,
    marginBottom: spacing.md,
    fontFamily: fontFamilies.body,
  },
  sendButtonWrapper: {
    position: 'relative',
  },
  sendButtonGlow: {
    position: 'absolute',
    top: -3, left: -3, right: -3, bottom: -3,
    borderRadius: radius.md + 3,
    borderWidth: 1,
    borderColor: v.gold,
    ...brassShadow,
  },
  sendButton: {
    backgroundColor: v.gold,
    paddingVertical: 14,
    borderRadius: radius.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: v.goldSoft,
  },
  buttonDisabled: { backgroundColor: v.taupe, borderColor: v.taupe },
  sendButtonText: {
    color: v.ink,
    fontSize: fontSize.md,
    fontFamily: fontFamilies.serif,
    fontWeight: '700',
    letterSpacing: 2.5,
    textTransform: 'uppercase',
  },
});
